### PR TITLE
Updates hyrax-preservation gem

### PR DESCRIPTION
**Pull request by afred**
Previously named just 'preservation', now named 'hyrax-preservation'.

### CODE REVIEW

**Comment by afred** [comment]
Whoops... forgot about having to change all of the references from `Preservation` to `Hyrax::Preservation`. Will fix this later, but will probably use the WGBH fork for demo tomorrow.

**Comment by afred** [comment]
@dlpierce @aploshay Please review and merge (or approve) if green.

**Comment by aploshay** [comment]
@afred Adding the `Hyrax::` looks good; why does it include the 3 changed `spec/fixtures/IU/40000000054496_20160213-082528/*.xml` files?

**Comment by afred** [comment]
@aploshay Gah.. that has to do with a test that needs cleaned up. Essentially, a tarball is committed as part of the repo, but when running the tests, it unpacks them, but then doesn't delete them. So they show up as changed files. I usually remember to leave them out of the commit, but here I forgot. I'll fix it. Stand by.

**Comment by afred** [comment]
@aploshay Ok, well, it looks like some other files from the test tarball may have been committed previously. Anyway, I removed the additional ones that you asked about, but the rest of them should probably be removed at a future date, and added to gitignore, and deleted after the tarball test is run to avoid them showing up as new/chaged files.

**Pull request merged**
