### PR TITLE
WGBH SIP preingest: put pbcore and fits in the same FileSet

### PR DESCRIPTION
**Pull request by aploshay**
Resolves HDM-840, HDM-841, HDM-847, HDM-850, HDM-851, HDM-853
Important notes:
* The distinct file uses assigned in the first commit will be changed or even refactored later; since ingesting multiple files to the same FileSet was broken, I just wanted to get some application of it 2+ files/FileSet established and working
* The issue with the 2nd+ file not ingesting results from IngestFileJob.perform_later not being robust against the job queue strategy being :inline vs. :async (the latter being the new default in Rails 5).  The 2nd commit (0b1f63d) seeks to address this by changing the call to .perform_now, which is robust against either job queue strategy.  The 3rd commit (868caaa) changes the job queue strategy for all 3 environments.
  * So a point of discussion here is whether folks want to keep either/both commits, add additional comments, or resolve this altogether differently.
  * An argument for _only_ doing the config change is that it avoids monkeypatching; a counterargument is that anyone changing their config values there would introduce a bug, so that at least merits commenting.
  * An argument for doing the monkeypatch is to make the job results robust against the configuration change; a counterargument is that we want to avoid monkeypatching the Hydra stack.
  * So this may merit some discussion if folks have strong feelings one way or another, but I do want to get this merged in quickly as multiple files/FileSet ingestion is broken in the meantime.  (Ideally, we use a version of curation_concerns that fixes this.)
* ~~The issue with file characterization assuming a fixed use of :original_file is fixed in c2865c8 -- again, ideally, we use a version of curation_concerns that fixes the issue, but I don't want to get stuck waiting on that.~~
* The issue with file characterization assuming a fixed use of :original_file is fixed in 3e9b83a -- again, ideally, we use a version of curation_concerns that fixes the issue, but I don't want to get stuck waiting on that.

### CODE REVIEW

**Comment by aploshay** [comment]
Some other ways to potentially resolve 2nd+ file ingest:
* If issue has been fixed in a more recent version of the Hydra stack, we could pull those changes
* If the issue is still outstanding in the most recent version of the Hydra stack, we could submit a fix for it
Those are better long-term fixes, but I didn't want to burn too much time on them before the WGBH launch.

**Comment by dlpierce** [comment]
I'll check the curation_concerns gem's specs to see if there is one that tries multiple files like we are trying to do.

**Comment by amolmkhedkar** [comment]
Adam and myself just found out I am getting an error on my machine when I run ingest on this branch.
We have resolved the error locally.

@dlpierce @afred Let us know if you guys are getting similar error.

This is the error:

rake aborted!
LoadError: original_file was not found
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/curation_concerns-1.6.3/app/jobs/characterize_job.rb:9:in `perform'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/i18n-0.8.0/lib/i18n.rb:257:in `with_locale'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:46:in `tag_logger'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:33:in `perform_now'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:22:in `block in execute'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/reloader.rb:67:in `wrap'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_execute_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:20:in `execute'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/queue_adapters/inline_adapter.rb:13:in `enqueue'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/enqueuing.rb:76:in `block in enqueue'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:15:in `block (3 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:46:in `tag_logger'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_enqueue_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/enqueuing.rb:72:in `enqueue'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/enqueuing.rb:18:in `perform_later'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/curation_concerns-1.6.3/app/jobs/ingest_file_job.rb:35:in `perform'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/i18n-0.8.0/lib/i18n.rb:257:in `with_locale'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:46:in `tag_logger'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:33:in `perform_now'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:16:in `perform_now'
/home/amolkhedkar/Desktop/phydo/lib/phydo/file_actor/ingest_file_now.rb:7:in `ingest_file'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/curation_concerns-1.6.3/app/actors/curation_concerns/actors/file_set_actor.rb:45:in `create_content'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:56:in `block in ingest_files'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:53:in `each'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:53:in `each_with_index'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:53:in `ingest_files'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:40:in `block in ingest_file_sets'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:33:in `each'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:33:in `ingest_file_sets'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:28:in `ingest'
/home/amolkhedkar/Desktop/phydo/app/jobs/ingest_yaml_job.rb:11:in `perform'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/i18n-0.8.0/lib/i18n.rb:257:in `with_locale'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:46:in `tag_logger'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:33:in `perform_now'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/activejob-5.0.1/lib/active_job/execution.rb:16:in `perform_now'
/home/amolkhedkar/Desktop/phydo/lib/tasks/ingest_yaml.rake:18:in `block (2 levels) in <top (required)>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/amolkhedkar/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => hydradam:ingest_yaml
(See full trace by running task with --trace)

**Comment by amolmkhedkar** [comment]
+1 Approved. 
I am fine with the changes in this PR.
@afred @dlpierce Let us know your thoughts.
Thanks.

**Comment by dlpierce** [comment]
Looks good to me now.

**Pull request merged**
